### ISSUE TITLE
Don't delete a GitHub default branch

### ISSUE THREAD

**Issue by MXWest** [genuinetools/ghb0t#7]
In the absence of a contribution guide, I've opened an issue here because I'd like to experiment with `ghb0t` at my organization. _Many_ of our repositories have a _different_ default branch, which in addition to (or instead of) our usage of `master` we would not wish to ever have deleted under any circumstances.

I'd like to try my hand at making that change, or if it was something already in your plans, maybe help with. Cheers!

**Comment by jessfraz** [comment]
Please make a PR that would be awesome thanks!
